[project]
name = "dlt-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bastien Winant", email = "armand.winant@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dlt[duckdb]>=1.29.1",
    "logfire>=4.39.0",
    "minsearch>=0.2.0",
    "openai>=2.50.0",
    "pydantic-ai>=2.21.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[project.scripts]
dlt-workshop = "dlt_workshop:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
